zookeeper:
    image: wurstmeister/zookeeper
    container_name: "zk"
    ports:
      - "2181:2181"
kafka:
    image: wurstmeister/kafka
    container_name: "kafka"
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_CREATE_TOPICS: "payara-kafka-mdb-topic:3:1"
    links:
    - zookeeper:zk
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

app:
  build: .
  container_name: "app"
  environment:
    - KAFKA_BROKER=kafka:9092
    - TOPIC_NAME=payara-kafka-mdb-topic

  ports:
      - "8080:8080"
  links:
    - kafka:kafka